# document：https://flutter.dev/docs/development/accessibility-and-localization/internationalization

arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
use-deferred-loading: false
